# Generated by Django 5.2.9 on 2026-01-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('minimum_people', models.PositiveIntegerField()),
                ('maximum_people', models.PositiveIntegerField()),
            ],
        ),
    ]
